version: '2.3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.1"
    restart: on-failure
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

    networks:
      - api

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.12.1"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - api

  app:
    image: "curco.app:latest"

    ports:
      - "3000:3000"

    volumes:
      - ../config:/curco/config:ro

    networks:
      - api

  api:
    image: "curco.api:latest"

    volumes:
      - ../config:/curco/config:ro

    ports:
      - "3001:3001"

    networks:
      - api

volumes:
  esdata1:

networks:
  api:
    driver: bridge
