version: '1.0'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1

    restart: on-failure

    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

     ports:
       - "5601:5601"


volumes:
  esdata1:
